name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish -c Release -o publish

      - name: Create Deployment Package
        run: |
          cd publish
          zip -r ../deployment.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Create Application Version
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          aws s3 cp deployment.zip \
          s3://elasticbeanstalk-ap-south-1-$ACCOUNT_ID/deployment-${{ github.run_number }}.zip

          aws elasticbeanstalk create-application-version \
          --application-name app-dev-ebs-01 \
          --version-label github-${{ github.run_number }} \
          --source-bundle S3Bucket=elasticbeanstalk-ap-south-1-$ACCOUNT_ID,S3Key=deployment-${{ github.run_number }}.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name App-dev-ebs-01-env \
          --version-label github-${{ github.run_number }}
